name: Publish Docker Image

on:
  push:
    branches:
      - master  # Adjust to your desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ravidevaki@gmail.com/Ravi@edureka123:latest .

    - name: Push the Docker image
      run: docker push ravidevaki/certproject-2:latest
